services:
  php:
    build: ./config
    environment:
      APACHE_DOCUMENT_ROOT: public/
      PHP_INI_MEMORY_LIMIT: 4g
      PHP_EXTENSIONS: gd intl amqp
    ports:
      - "80:80" # apache2
      - "8888:8888" # watch admin
      - "9998:9998" # watch storefront proxy (not needed if you start with "make watch-storefront")
      - "9999:9999" # watch storefront
    volumes:
      - ./:/var/www/html:cached
      - "${GIT_SSH_KEY_PATH:-~/.ssh/id_rsa}:/home/docker/.ssh/id_rsa:ro"
      - "${GIT_SSH_KEY_PATH:-~/.ssh/id_rsa}.pub:/home/docker/.ssh/id_rsa.pub:ro"
    networks:
      - web

  database:
    image: mysql:8.0.29-oracle
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-shopware}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-shopware}
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - ./config/etc/mysql/my.cnf:/etc/my.cnf
      - db-data:/var/lib/mysql:rw
    networks:
      - web
  
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - web

  redis:
    image: redis:6.0.15
    command:
      [
        redis-server,
        --maxmemory 128mb,
        --maxmemory-policy volatile-lru,
        --save "",
      ]
    networks:
      - web
  
  opensearch:
    image: opensearchproject/opensearch:2
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    environment:
      discovery.type: single-node
      plugins.security.disabled: true
      OPENSEARCH_INITIAL_ADMIN_PASSWORD: "${OPENSEARCH_INITIAL_ADMIN_PASSWORD:-VeryStrongPassword123!}"
    ports:
      - "9200:9200"
    networks:
      - web
      
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
    

volumes:
  db-data:
    driver: local
  opensearch-data:
    driver: local

networks:
  web:
    driver: bridge
    external: false
